Repository mohdfawad99/next-gallery-app, pull requests merged in 2023-10, with the labels that each got.

#1 Peñon de Comasagua image added
  app/data.json
Labels: hacktoberfest-accepted

#2 Wasdale Head added
  app/data.json
Labels: hacktoberfest, hacktoberfest-accepted

#6 Code optimising
  app/data.js
  app/page.tsx
  next.config.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 Revert "Code optimising"
  app/data.json
  app/page.tsx
  next.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#4 Iguazu Falls added
  app/data.json
Labels: hacktoberfest, hacktoberfest-accepted

#8 Update data.json
  app/data.json
Labels: hacktoberfest, hacktoberfest-accepted

#9 Update data.json
  app/data.json
Labels: hacktoberfest, hacktoberfest-accepted

#11 Update data.json
  app/data.json
Labels: hacktoberfest, hacktoberfest-accepted
